### ISSUE TITLE
Twitch Chat Bot not connecting

### ISSUE THREAD

**Issue by roronetwork** [jujoco/twitch-multitask-task-list-overlay#10]
The chat bot isn't connecting - the OBS log error looks like this: 10:03:10.332: [obs-browser: 'Tasklist Bot'] Error: Connection dropped. Reconnecting in 64000 milliseconds... (http://absolute/C:/Twitch/twitch-multitask-task-list-overlay-main/dist/taskBot.iife.js:1)

the oauth code and username, etc are all correct

thank you!

**Comment by jujoco** [comment]
Thanks for reporting this issue. 
I'll be streaming today. stop by and we can chat about it. 

I will attempt to produce the same error and implement a fix. 

twtich @ JujocoCS

**Comment by jujoco** [comment]
will be closing issue. the issue you are experiencing is due to a syntax error.  please visit my challenge to discuss
