### ISSUE TITLE
Adding User Avatars

### ISSUE THREAD

**Issue by alexvarha** [jujoco/twitch-multitask-task-list-overlay#11]
As a viewer I'd like to see my & other people's avatars in the task lists next to their usernames when I watch the task list scroll on the screen.

According to [twitchio's bot builder documentation](https://twitchio.dev/en/stable/reference.html#twitchio.User.profile_image) there's a profile_image variable in the twitch's API.

**Comment by jujoco** [comment]
We discovered this request won't be possible for this project.  
Retrieving the profile image of users requires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens).

user-access token is outside the scope of this project. 
closing Issue.
