### ISSUE TITLE
bot should reply with string, not with task id

### ISSUE THREAD

**Issue by alexvarha** [jujoco/twitch-multitask-task-list-overlay#14]
as a user I'd like to see the content of the task when the bot responds to me in chat, citing the content of the task instead of its number (the way other bots handle task management)

<img width="236" alt="chrome_mhXBUceICL" src="https://github.com/jujoco/twitch-multitask-task-list-overlay/assets/125912906/8d9db38d-9af1-4c20-92bf-2b9dac45ea4a">

**Comment by jujoco** [comment]
got it. give me about a week to add this.

**Comment by alexvarha** [comment]
no worries, it's just a suggestion

**Comment by jujoco** [comment]
@alexvarha Done! thanks for the request! 🎉
