### ISSUE TITLE
Feature Request: Option to Exclude Users to Prevent Spamming the Task List

### ISSUE THREAD

**Issue by rez1coder** [jujoco/twitch-multitask-task-list-overlay#18]
I love that users can utilize the task list, but sometimes spammers may take advantage of it. It would be wonderful to have an option to exclude specific users to keep the task list clean and productive.

**Comment by jujoco** [comment]
great idea! 
help brainstorm command names.
Potential command name for banning users. 
!taskbanuser, 
!listbanuser, 
!taskunbanuser
etc.

**Comment by rez1coder** [comment]
These are good.
```
!TaskBanUser
!TaskUnbanUser
!ListBannedUsers
```
Since you wrote the commands in smaller case, these should do:
```
!taskban
!taskunban
!listban
```

**Comment by jujoco** [comment]
It turns out Twitch Chat already has a **Ban** and **Timeout** feature available to streamers to guard against spammers.
See image 
<img width="338" alt="Screenshot 2024-11-24 at 1 55 27 PM" src="https://github.com/user-attachments/assets/7ec17455-64cc-4fba-839f-3154c218030d">

**Comment by jujoco** [comment]
closing issue.
