### ISSUE TITLE
when is the invalidCommand response triggered?

### ISSUE THREAD

**Issue by alexvarha** [jujoco/twitch-multitask-task-list-overlay#24]
As far as i've seen the bot remains silent when it doesn't notice a valid command. 

![image](https://github.com/user-attachments/assets/e3b18420-8333-4ea2-8717-85903ecaeaad)

What types of errors does `invalidCommand: "Invalid command: {message}. Try !help"` can the bot identify?

**Comment by jujoco** [comment]
@alexvarha, errors messages are only triggered when an existing command is misused.
