### ISSUE TITLE
brianstorming: Add per user tasks completed count

### ISSUE THREAD

**Issue by jtmusselman** [jujoco/twitch-multitask-task-list-overlay#3]
I suggested adding task stats to the card for users. This would be a new line at the bottom of the users card and display lifetime tasks completed and tasks completed today

[Mockup](https://excalidraw.com/#json=K7Qvq20VIT6EqhUq26i6U,gQfqORBNkl86kwVGLml_hQ)

**Comment by jujoco** [comment]
discussing the possibility of adding a feature that would keep track of an individual's completed tasks. 
this feature would be configurable & enabled through the configs.js file

![Screenshot 2024-05-21 at 7 54 02 PM](https://github.com/jujoco/Twitch-chatbot-multitask-task-list-overlay/assets/34930292/c3fed709-0056-4f87-890d-e59bf249c52c)

**Comment by alexvarha** [comment]
interesting! That would require keeping a log file then?

Might be better to stick the numbers on the same line as the user's name, to avoid making the cards too long - otherwise if you have a lot of different users with tasks the scrolling through the list will take more time

**Comment by jujoco** [comment]
Hi @alexvarha - you're correct, a log file would be needed to maintain a user's lifetime count but we are definitely not going to maintain a lifetime count.   

All User data (username & tasks) is removed from the localDB once a user is removed from the list or once a user deletes all their tasks.  There is also a limited number of tasks a user can create. I added this limit to prevent spam abuse and visual clutter. In short, displaying a User complete count offers very little value to users and only adds visual clutter. 

appreciate your curiosity and questions.

**Comment by jujoco** [comment]
Closing this brainstorming feature request.
